const SubmissionStatus = {
  SUCCESS: 'SUCCESS',
  COMPILATION_ERROR: 'COMPILATION_ERROR',
  TEST_FAILED: 'TEST_FAILED',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  INVALID_EXERCISE: 'INVALID_EXERCISE',
  INVALID_FILES: 'INVALID_FILES',
};

module.exports = SubmissionStatus;
